[Sound Theme]
Name=Oxygen
Name[ar]=أكسجين
Name[ca]=Oxygen
Name[ca@valencia]=Oxygen
Name[de]=Oxygen
Name[eo]=Oxygen
Name[es]=Oxígeno
Name[eu]=Oxygen
Name[ia]=Oxygen
Name[it]=Oxygen
Name[ka]=Oxygen
Name[ko]=Oxygen
Name[nl]=Oxygen
Name[pl]=Tlen
Name[sl]=Oxygen
Name[tr]=Oksijen
Name[uk]=Oxygen
Name[x-test]=xxOxygenxx
Name[zh_CN]=Oxygen 轻氧
Comment=Oxygen Sound Theme for KDE Plasma
Directories=stereo
Example=theme-demo

[stereo]
OutputProfile=stereo
